In [1]:
#import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#get data
data = pd.read_csv("/content/weatherAUS.csv")
data.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [4]:
data.shape

(145460, 23)

In [5]:
data.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [6]:
data = data.dropna()

In [7]:
data.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
6049  2009-01-01    Cobar     17.9     35.2       0.0         12.0      12.3   
6050  2009-01-02    Cobar     18.4     28.9       0.0         14.8      13.0   
6052  2009-01-04    Cobar     19.4     37.6       0.0         10.8      10.6   
6053  2009-01-05    Cobar     21.9     38.4       0.0         11.4      12.2   
6054  2009-01-06    Cobar     24.2     41.0       0.0         11.2       8.4   

     WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
6049         SSW           48.0        ENE  ...        20.0         13.0   
6050           S           37.0        SSE  ...        30.0          8.0   
6052         NNE           46.0        NNE  ...        42.0         22.0   
6053         WNW           31.0        WNW  ...        37.0         22.0   
6054         WNW           35.0         NW  ...        19.0         15.0   

      Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
6049       1006.3       1004.4       2.0       5.0     26.6     33.4   
6050       1012.9       1012.1       1.0       1.0     20.3     27.0   
6052       1012.3       1009.2       1.0       6.0     28.7     34.9   
6053       1012.7       1009.1       1.0       5.0     29.1     35.6   
6054       1010.7       1007.4       1.0       6.0     33.6     37.6   

      RainToday  RainTomorrow  
6049         No            No  
6050         No            No  
6052         No            No  
6053         No            No  
6054         No            No  

[5 rows x 23 columns]

In [8]:
data.isnull().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [9]:
#Replace the target variable i.e from categorical to number
data = data.replace({'RainTomorrow':{'Yes':1, 'No':0}})

In [10]:
data.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
6049  2009-01-01    Cobar     17.9     35.2       0.0         12.0      12.3   
6050  2009-01-02    Cobar     18.4     28.9       0.0         14.8      13.0   
6052  2009-01-04    Cobar     19.4     37.6       0.0         10.8      10.6   
6053  2009-01-05    Cobar     21.9     38.4       0.0         11.4      12.2   
6054  2009-01-06    Cobar     24.2     41.0       0.0         11.2       8.4   

     WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
6049         SSW           48.0        ENE  ...        20.0         13.0   
6050           S           37.0        SSE  ...        30.0          8.0   
6052         NNE           46.0        NNE  ...        42.0         22.0   
6053         WNW           31.0        WNW  ...        37.0         22.0   
6054         WNW           35.0         NW  ...        19.0         15.0   

      Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
6049       1006.3       1004.4       2.0       5.0     26.6     33.4   
6050       1012.9       1012.1       1.0       1.0     20.3     27.0   
6052       1012.3       1009.2       1.0       6.0     28.7     34.9   
6053       1012.7       1009.1       1.0       5.0     29.1     35.6   
6054       1010.7       1007.4       1.0       6.0     33.6     37.6   

      RainToday  RainTomorrow  
6049         No             0  
6050         No             0  
6052         No             0  
6053         No             0  
6054         No             0  

[5 rows x 23 columns]

In [13]:
#Separate the numeric from the categorical
numerical_col = []
categorical_col = []


# Iterate through each column to check its data type
for col in data.columns:
    if data[col].dtype == 'object':
        categorical_col.append(col)
    else:
        numerical_col.append(col)

In [15]:
numerical_col

['MinTemp',
 'MaxTemp',
 'Rainfall',
 'Evaporation',
 'Sunshine',
 'WindGustSpeed',
 'WindSpeed9am',
 'WindSpeed3pm',
 'Humidity9am',
 'Humidity3pm',
 'Pressure9am',
 'Pressure3pm',
 'Cloud9am',
 'Cloud3pm',
 'Temp9am',
 'Temp3pm',
 'RainTomorrow']

In [16]:
categorical_col

['Date', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday']

In [18]:
#Let's see the correlation the numerical with the target variable
data[numerical_col].corr()['RainTomorrow'].sort_values(ascending=False)

RainTomorrow     1.000000
Humidity3pm      0.455358
Cloud3pm         0.388574
Cloud9am         0.323972
Humidity9am      0.271033
Rainfall         0.254342
WindGustSpeed    0.233158
WindSpeed3pm     0.088862
MinTemp          0.087428
WindSpeed9am     0.083904
Temp9am         -0.018179
Evaporation     -0.130002
MaxTemp         -0.147467
Temp3pm         -0.183586
Pressure3pm     -0.230418
Pressure9am     -0.254816
Sunshine        -0.453407
Name: RainTomorrow, dtype: float64

In [19]:
#convert the categorical varibles to numerical variables using label encoder
data[categorical_col].nunique()

Date           3416
Location         26
WindGustDir      16
WindDir9am       16
WindDir3pm       16
RainToday         2
dtype: int64

In [20]:
#since we dont need the data column
data.drop(columns=['Date'], inplace=True)
categorical_col.remove('Date')

In [21]:
#label encoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in categorical_col:
    data[col] = le.fit_transform(data[col])

In [22]:
data.head()

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
6049         4     17.9     35.2       0.0         12.0      12.3   
6050         4     18.4     28.9       0.0         14.8      13.0   
6052         4     19.4     37.6       0.0         10.8      10.6   
6053         4     21.9     38.4       0.0         11.4      12.2   
6054         4     24.2     41.0       0.0         11.2       8.4   

      WindGustDir  WindGustSpeed  WindDir9am  WindDir3pm  ...  Humidity9am  \
6049           11           48.0           1          12  ...         20.0   
6050            8           37.0          10          10  ...         30.0   
6052            5           46.0           5           6  ...         42.0   
6053           14           31.0          14          15  ...         37.0   
6054           14           35.0           7          14  ...         19.0   

      Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
6049         13.0       1006.3       1004.4       2.0       5.0     26.6   
6050          8.0       1012.9       1012.1       1.0       1.0     20.3   
6052         22.0       1012.3       1009.2       1.0       6.0     28.7   
6053         22.0       1012.7       1009.1       1.0       5.0     29.1   
6054         15.0       1010.7       1007.4       1.0       6.0     33.6   

      Temp3pm  RainToday  RainTomorrow  
6049     33.4          0             0  
6050     27.0          0             0  
6052     34.9          0             0  
6053     35.6          0             0  
6054     37.6          0             0  

[5 rows x 22 columns]

In [23]:
#Let's split the data
X = data.drop(columns=['RainTomorrow'])
y = data['RainTomorrow']

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
X_train.shape, y_train.shape

((45136, 21), (45136,))

In [27]:
X_test.shape, y_test.shape

((11284, 21), (11284,))

LOGISTIC REGRESSION

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_prediction = lr.predict(X_test)
# Evaluating the model
print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_prediction))
print("Classification Report:\n", classification_report(y_test, lr_prediction))
print("Confusion Matrix:\n", confusion_matrix(y_test, lr_prediction))

Logistic Regression Accuracy: 0.8543069833392414
Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.95      0.91      8799
           1       0.75      0.51      0.61      2485

    accuracy                           0.85     11284
   macro avg       0.81      0.73      0.76     11284
weighted avg       0.85      0.85      0.84     11284

Confusion Matrix:
 [[8372  427]
 [1217 1268]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DECISION TREE

In [31]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt_prediction = dt.predict(X_test)
# Evaluating the model
print("Logistic Regression Accuracy:", accuracy_score(y_test, dt_prediction))
print("Classification Report:\n", classification_report(y_test, dt_prediction))
print("Confusion Matrix:\n", confusion_matrix(y_test, dt_prediction))

Logistic Regression Accuracy: 0.792803970223325
Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.86      0.87      8799
           1       0.53      0.54      0.54      2485

    accuracy                           0.79     11284
   macro avg       0.70      0.70      0.70     11284
weighted avg       0.79      0.79      0.79     11284

Confusion Matrix:
 [[7595 1204]
 [1134 1351]]


RANDOM FOREST

In [32]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf_prediction = rf.predict(X_test)
# Evaluating the model
print("Logistic Regression Accuracy:", accuracy_score(y_test, rf_prediction))
print("Classification Report:\n", classification_report(y_test, rf_prediction))
print("Confusion Matrix:\n", confusion_matrix(y_test, rf_prediction))

Logistic Regression Accuracy: 0.8619283941864587
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.96      0.92      8799
           1       0.77      0.53      0.63      2485

    accuracy                           0.86     11284
   macro avg       0.82      0.74      0.77     11284
weighted avg       0.85      0.86      0.85     11284

Confusion Matrix:
 [[8406  393]
 [1165 1320]]


XGB

In [33]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)
xgb_prediction = xgb.predict(X_test)
# Evaluating the model
print("Logistic Regression Accuracy:", accuracy_score(y_test, xgb_prediction))
print("Classification Report:\n", classification_report(y_test, xgb_prediction))
print("Confusion Matrix:\n", confusion_matrix(y_test, xgb_prediction))

Logistic Regression Accuracy: 0.8613080467919177
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.94      0.91      8799
           1       0.74      0.58      0.65      2485

    accuracy                           0.86     11284
   macro avg       0.81      0.76      0.78     11284
weighted avg       0.85      0.86      0.85     11284

Confusion Matrix:
 [[8286  513]
 [1052 1433]]


SUPPORT VECTOR

In [34]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)
svc_prediction = svc.predict(X_test)
# Evaluating the model
print("Logistic Regression Accuracy:", accuracy_score(y_test, svc_prediction))
print("Classification Report:\n", classification_report(y_test, svc_prediction))
print("Confusion Matrix:\n", confusion_matrix(y_test, svc_prediction))

Logistic Regression Accuracy: 0.8426976249556895
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.98      0.91      8799
           1       0.83      0.36      0.50      2485

    accuracy                           0.84     11284
   macro avg       0.84      0.67      0.70     11284
weighted avg       0.84      0.84      0.82     11284

Confusion Matrix:
 [[8612  187]
 [1588  897]]


THE BEST MODEL TO USE IS: RANDOM FOREST